name: Check Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if CHANGELOG.md is modified
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changelog:
              - 'CHANGELOG.md'

      - name: Fail if CHANGELOG.md is not modified
        if: steps.changes.outputs.changelog == 'false'
        run: |
          echo "Error: CHANGELOG.md must be modified in this Pull Request."
          exit 1

      - name: Fail if CHANGELOG.md contains "## [Unreleased]"
        run: |
          if grep -q "## \[Unreleased\]" CHANGELOG.md; then
            echo "Error: CHANGELOG.md should not contain '## [Unreleased]'. Please replace it with a versioned header."
            exit 1
          fi
